### ISSUE TITLE
Fix for CHANGELOG format.

### ISSUE THREAD

**Issue by zw963** [oggy/ritual#2]
Hi,  i use emacs editor, it exists one builtin change-log-mode, it can format change log like this: (please see a screenshot)

![image](https://user-images.githubusercontent.com/549126/164761233-ca2fedd8-c510-42ad-b460-3e61cfd3b3fa.png)

when i pressing enter key, it always add a TAB before all lines in CHANGELOG file, it hard to change to this behavior, because
those all emacs builtin and not offer a options for change this, please check following screenshot.

![image](https://user-images.githubusercontent.com/549126/164761756-c601ce53-3ae5-488f-bf09-b2bdf1a155c5.png)

So, it is a pain when i want to add a CHANGELOG, because it give me a error msg like this:

```
 ╰─ $ rake patch release
rake aborted!
Ritual::Changelog::Error: No LATEST entry in CHANGELOG - did you forget to update it?
/home/common/.rvm/gems/ruby-3.1.0@pryx/gems/ritual-0.4.1/lib/ritual/changelog.rb:17:in `set_latest_version'
/home/common/.rvm/gems/ruby-3.1.0@pryx/gems/ritual-0.4.1/lib/ritual.rb:29:in `block (2 levels) in <top (required)>'
Tasks: TOP => release => repo:bump
(See full trace by running task with --trace)
```

so, do you consider accept a patch for fix this?

```diff
diff --git a/lib/ritual/changelog.rb b/lib/ritual/changelog.rb
index c3bfa2a..ae77814 100644
--- a/lib/ritual/changelog.rb
+++ b/lib/ritual/changelog.rb
@@ -13,7 +13,7 @@ module Ritual
         raise Error, "Don't release without a CHANGELOG!"
       text = File.read(path)
       heading = "#{version} #{Date.today.strftime('%Y-%m-%d')}"
-      text.sub!(/^(== )LATEST$/i, "\\1#{heading}") or
+      text.sub!(/^(\s*== )LATEST$/i, "\\1#{heading}") or
         raise Error, "No LATEST entry in CHANGELOG - did you forget to update it?"
       open(path, 'w'){|f| f.print text}
     end
```

**Comment by zw963** [comment]
This little changes take effect me a lot,  because it be used in gemspec file, so, i can't use it on bundle, that means,
i have to install from rubygems directly, can not use my git repo instead, i have to local gem source code manually for this work.

Please check PR

https://github.com/oggy/ritual/pull/3/files

**Comment by oggy** [comment]
Looks good -- thanks!
